# TCL File Generated by Component Editor 22.1
# Wed Nov 22 16:53:16 EST 2023
# DO NOT MODIFY


# 
# dfe "dfe" v1.0
#  2023.11.22.16:53:16
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dfe
# 
set_module_property DESCRIPTION ""
set_module_property NAME dfe
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dfe
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DFE
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file decision_maker.sv SYSTEM_VERILOG PATH ../rtl/Rx_sim/decision_maker.sv
add_fileset_file dfe.sv SYSTEM_VERILOG PATH ../rtl/Rx_sim/dfe.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PULSE_RESPONSE_LENGTH INTEGER 2
set_parameter_property PULSE_RESPONSE_LENGTH DEFAULT_VALUE 2
set_parameter_property PULSE_RESPONSE_LENGTH DISPLAY_NAME PULSE_RESPONSE_LENGTH
set_parameter_property PULSE_RESPONSE_LENGTH TYPE INTEGER
set_parameter_property PULSE_RESPONSE_LENGTH UNITS None
set_parameter_property PULSE_RESPONSE_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PULSE_RESPONSE_LENGTH HDL_PARAMETER true
add_parameter SIGNAL_RESOLUTION INTEGER 8
set_parameter_property SIGNAL_RESOLUTION DEFAULT_VALUE 8
set_parameter_property SIGNAL_RESOLUTION DISPLAY_NAME SIGNAL_RESOLUTION
set_parameter_property SIGNAL_RESOLUTION TYPE INTEGER
set_parameter_property SIGNAL_RESOLUTION UNITS None
set_parameter_property SIGNAL_RESOLUTION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIGNAL_RESOLUTION HDL_PARAMETER true
add_parameter SYMBOL_SEPERATION INTEGER 56
set_parameter_property SYMBOL_SEPERATION DEFAULT_VALUE 56
set_parameter_property SYMBOL_SEPERATION DISPLAY_NAME SYMBOL_SEPERATION
set_parameter_property SYMBOL_SEPERATION TYPE INTEGER
set_parameter_property SYMBOL_SEPERATION UNITS None
set_parameter_property SYMBOL_SEPERATION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOL_SEPERATION HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rstn reset_n Input 1


# 
# connection point noise
# 
add_interface noise conduit end
set_interface_property noise associatedClock clock
set_interface_property noise associatedReset reset_n
set_interface_property noise ENABLED true
set_interface_property noise EXPORT_OF ""
set_interface_property noise PORT_NAME_MAP ""
set_interface_property noise CMSIS_SVD_VARIABLES ""
set_interface_property noise SVD_ADDRESS_GROUP ""

add_interface_port noise noise noise Input 8


# 
# connection point train_data
# 
add_interface train_data conduit end
set_interface_property train_data associatedClock clock
set_interface_property train_data associatedReset reset_n
set_interface_property train_data ENABLED true
set_interface_property train_data EXPORT_OF ""
set_interface_property train_data PORT_NAME_MAP ""
set_interface_property train_data CMSIS_SVD_VARIABLES ""
set_interface_property train_data SVD_ADDRESS_GROUP ""

add_interface_port train_data train_data train_data Input "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port train_data train_data_valid train_data_valid Input 1


# 
# connection point dfe_in
# 
add_interface dfe_in conduit end
set_interface_property dfe_in associatedClock clock
set_interface_property dfe_in associatedReset reset_n
set_interface_property dfe_in ENABLED true
set_interface_property dfe_in EXPORT_OF ""
set_interface_property dfe_in PORT_NAME_MAP ""
set_interface_property dfe_in CMSIS_SVD_VARIABLES ""
set_interface_property dfe_in SVD_ADDRESS_GROUP ""

add_interface_port dfe_in signal_in signal_in Input "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port dfe_in signal_in_valid signal_in_valid Input 1


# 
# connection point dfe_out
# 
add_interface dfe_out conduit end
set_interface_property dfe_out associatedClock clock
set_interface_property dfe_out associatedReset reset_n
set_interface_property dfe_out ENABLED true
set_interface_property dfe_out EXPORT_OF ""
set_interface_property dfe_out PORT_NAME_MAP ""
set_interface_property dfe_out CMSIS_SVD_VARIABLES ""
set_interface_property dfe_out SVD_ADDRESS_GROUP ""

add_interface_port dfe_out signal_out signal_out Output "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port dfe_out signal_out_valid signal_out_valid Output 1

