# TCL File Generated by Component Editor 22.1
# Fri Oct 13 19:34:27 EDT 2023
# DO NOT MODIFY


# 
# gray_decoder "gray_decoder" v1.0
#  2023.10.13.19:34:27
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gray_decoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME gray_decoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gray_decoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL grey_decode
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gray_decoder.v VERILOG PATH ../rtl/Tx_sim/gray_decoder.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point data_out
# 
add_interface data_out conduit end
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset ""
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out data_out data_out Output 1
add_interface_port data_out data_out_valid data_out_valid Output 1


# 
# connection point rstn
# 
add_interface rstn reset end
set_interface_property rstn associatedClock clock
set_interface_property rstn synchronousEdges DEASSERT
set_interface_property rstn ENABLED true
set_interface_property rstn EXPORT_OF ""
set_interface_property rstn PORT_NAME_MAP ""
set_interface_property rstn CMSIS_SVD_VARIABLES ""
set_interface_property rstn SVD_ADDRESS_GROUP ""

add_interface_port rstn rstn reset_n Input 1


# 
# connection point symbol_in
# 
add_interface symbol_in conduit end
set_interface_property symbol_in associatedClock clock
set_interface_property symbol_in associatedReset ""
set_interface_property symbol_in ENABLED true
set_interface_property symbol_in EXPORT_OF ""
set_interface_property symbol_in PORT_NAME_MAP ""
set_interface_property symbol_in CMSIS_SVD_VARIABLES ""
set_interface_property symbol_in SVD_ADDRESS_GROUP ""

add_interface_port symbol_in symbol_in symbol_in Input 2
add_interface_port symbol_in symbol_in_valid symbol_in_valid Input 1

