# TCL File Generated by Component Editor 22.1
# Wed Nov 22 13:13:08 EST 2023
# DO NOT MODIFY


# 
# pam4_decoder "pam4_decoder" v1.0
#  2023.11.22.13:13:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pam4_decoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME pam4_decoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pam4_decoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pam_4_decode
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PAM_4_decoder.sv SYSTEM_VERILOG PATH ../rtl/Tx_sim/PAM_4_decoder.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SIGNAL_RESOLUTION INTEGER 8
set_parameter_property SIGNAL_RESOLUTION DEFAULT_VALUE 8
set_parameter_property SIGNAL_RESOLUTION DISPLAY_NAME SIGNAL_RESOLUTION
set_parameter_property SIGNAL_RESOLUTION TYPE INTEGER
set_parameter_property SIGNAL_RESOLUTION UNITS None
set_parameter_property SIGNAL_RESOLUTION HDL_PARAMETER true
add_parameter SYMBOL_SEPERATION INTEGER 56
set_parameter_property SYMBOL_SEPERATION DEFAULT_VALUE 56
set_parameter_property SYMBOL_SEPERATION DISPLAY_NAME SYMBOL_SEPERATION
set_parameter_property SYMBOL_SEPERATION TYPE INTEGER
set_parameter_property SYMBOL_SEPERATION UNITS None
set_parameter_property SYMBOL_SEPERATION HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rstn reset_n Input 1


# 
# connection point rx_pam4_input
# 
add_interface rx_pam4_input conduit end
set_interface_property rx_pam4_input associatedClock clock
set_interface_property rx_pam4_input associatedReset reset_n
set_interface_property rx_pam4_input ENABLED true
set_interface_property rx_pam4_input EXPORT_OF ""
set_interface_property rx_pam4_input PORT_NAME_MAP ""
set_interface_property rx_pam4_input CMSIS_SVD_VARIABLES ""
set_interface_property rx_pam4_input SVD_ADDRESS_GROUP ""

add_interface_port rx_pam4_input voltage_level_in voltage_level_in Input "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port rx_pam4_input voltage_level_in_valid voltage_level_in_valid Input 1


# 
# connection point rx_pam4_output
# 
add_interface rx_pam4_output conduit end
set_interface_property rx_pam4_output associatedClock clock
set_interface_property rx_pam4_output associatedReset reset_n
set_interface_property rx_pam4_output ENABLED true
set_interface_property rx_pam4_output EXPORT_OF ""
set_interface_property rx_pam4_output PORT_NAME_MAP ""
set_interface_property rx_pam4_output CMSIS_SVD_VARIABLES ""
set_interface_property rx_pam4_output SVD_ADDRESS_GROUP ""

add_interface_port rx_pam4_output symbol_out symbol_out Output 2
add_interface_port rx_pam4_output symbol_out_valid symbol_out_valid Output 1

