# TCL File Generated by Component Editor 22.1
# Sun Oct 15 22:07:54 EDT 2023
# DO NOT MODIFY


# 
# PAM_encoder "PAM_encoder" v1.0
#  2023.10.15.22:07:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module PAM_encoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME PAM_encoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME PAM_encoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pam_4_encode
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PAM_4_encoder.sv SYSTEM_VERILOG PATH ../rtl/Tx_sim/PAM_4_encoder.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SIGNAL_RESOLUTION INTEGER 8
set_parameter_property SIGNAL_RESOLUTION DEFAULT_VALUE 8
set_parameter_property SIGNAL_RESOLUTION DISPLAY_NAME SIGNAL_RESOLUTION
set_parameter_property SIGNAL_RESOLUTION TYPE INTEGER
set_parameter_property SIGNAL_RESOLUTION UNITS None
set_parameter_property SIGNAL_RESOLUTION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIGNAL_RESOLUTION HDL_PARAMETER true
add_parameter SYMBOL_SEPERATION INTEGER 56
set_parameter_property SYMBOL_SEPERATION DEFAULT_VALUE 56
set_parameter_property SYMBOL_SEPERATION DISPLAY_NAME SYMBOL_SEPERATION
set_parameter_property SYMBOL_SEPERATION TYPE INTEGER
set_parameter_property SYMBOL_SEPERATION UNITS None
set_parameter_property SYMBOL_SEPERATION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOL_SEPERATION HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point rstn
# 
add_interface rstn reset end
set_interface_property rstn associatedClock clock
set_interface_property rstn synchronousEdges DEASSERT
set_interface_property rstn ENABLED true
set_interface_property rstn EXPORT_OF ""
set_interface_property rstn PORT_NAME_MAP ""
set_interface_property rstn CMSIS_SVD_VARIABLES ""
set_interface_property rstn SVD_ADDRESS_GROUP ""

add_interface_port rstn rstn reset_n Input 1


# 
# connection point symbol_in
# 
add_interface symbol_in conduit end
set_interface_property symbol_in associatedClock clock
set_interface_property symbol_in associatedReset rstn
set_interface_property symbol_in ENABLED true
set_interface_property symbol_in EXPORT_OF ""
set_interface_property symbol_in PORT_NAME_MAP ""
set_interface_property symbol_in CMSIS_SVD_VARIABLES ""
set_interface_property symbol_in SVD_ADDRESS_GROUP ""

add_interface_port symbol_in symbol_in symbol_in Input 2
add_interface_port symbol_in symbol_in_valid symbol_in_valid Input 1


# 
# connection point Voltage_level_out
# 
add_interface Voltage_level_out conduit end
set_interface_property Voltage_level_out associatedClock clock
set_interface_property Voltage_level_out associatedReset rstn
set_interface_property Voltage_level_out ENABLED true
set_interface_property Voltage_level_out EXPORT_OF ""
set_interface_property Voltage_level_out PORT_NAME_MAP ""
set_interface_property Voltage_level_out CMSIS_SVD_VARIABLES ""
set_interface_property Voltage_level_out SVD_ADDRESS_GROUP ""

add_interface_port Voltage_level_out voltage_level_out voltage_level_out Output "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port Voltage_level_out voltage_level_out_valid voltage_level_out_valid Output 1

