# TCL File Generated by Component Editor 22.1
# Sun Nov 12 22:05:21 EST 2023
# DO NOT MODIFY


# 
# channel_module "channel_module" v1.0
#  2023.11.12.22:05:21
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module channel_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME channel_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME channel_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ISI_channel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file channel_model.sv SYSTEM_VERILOG PATH ../rtl/channel_sim/channel_model.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PULSE_RESPONSE_LENGTH INTEGER 2
set_parameter_property PULSE_RESPONSE_LENGTH DEFAULT_VALUE 2
set_parameter_property PULSE_RESPONSE_LENGTH DISPLAY_NAME PULSE_RESPONSE_LENGTH
set_parameter_property PULSE_RESPONSE_LENGTH TYPE INTEGER
set_parameter_property PULSE_RESPONSE_LENGTH UNITS None
set_parameter_property PULSE_RESPONSE_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PULSE_RESPONSE_LENGTH HDL_PARAMETER true
add_parameter SIGNAL_RESOLUTION INTEGER 8
set_parameter_property SIGNAL_RESOLUTION DEFAULT_VALUE 8
set_parameter_property SIGNAL_RESOLUTION DISPLAY_NAME SIGNAL_RESOLUTION
set_parameter_property SIGNAL_RESOLUTION TYPE INTEGER
set_parameter_property SIGNAL_RESOLUTION UNITS None
set_parameter_property SIGNAL_RESOLUTION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIGNAL_RESOLUTION HDL_PARAMETER true
add_parameter SYMBOL_SEPERATION INTEGER 56
set_parameter_property SYMBOL_SEPERATION DEFAULT_VALUE 56
set_parameter_property SYMBOL_SEPERATION DISPLAY_NAME SYMBOL_SEPERATION
set_parameter_property SYMBOL_SEPERATION TYPE INTEGER
set_parameter_property SYMBOL_SEPERATION UNITS None
set_parameter_property SYMBOL_SEPERATION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOL_SEPERATION HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rstn reset_n Input 1


# 
# connection point channel_input
# 
add_interface channel_input conduit end
set_interface_property channel_input associatedClock clock
set_interface_property channel_input associatedReset reset_n
set_interface_property channel_input ENABLED true
set_interface_property channel_input EXPORT_OF ""
set_interface_property channel_input PORT_NAME_MAP ""
set_interface_property channel_input CMSIS_SVD_VARIABLES ""
set_interface_property channel_input SVD_ADDRESS_GROUP ""

add_interface_port channel_input signal_in signal_in Input "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port channel_input signal_in_valid signal_in_valid Input 1


# 
# connection point channel_output
# 
add_interface channel_output conduit end
set_interface_property channel_output associatedClock clock
set_interface_property channel_output associatedReset reset_n
set_interface_property channel_output ENABLED true
set_interface_property channel_output EXPORT_OF ""
set_interface_property channel_output PORT_NAME_MAP ""
set_interface_property channel_output CMSIS_SVD_VARIABLES ""
set_interface_property channel_output SVD_ADDRESS_GROUP ""

add_interface_port channel_output signal_out signal_out Output "((SIGNAL_RESOLUTION-1)) - (0) + 1"
add_interface_port channel_output signal_out_valid signal_out_valid Output 1

